### ISSUE TITLE
Add {ggpattern} to `packages.json`?

### ISSUE THREAD

**Issue by trevorld** [coolbutuseless/coolbutuseless.r-universe.dev#1]
* I haven't setup R-universe for myself but all CRAN packages I maintain auto-show up in R-universe except for `{ggpattern}`
* I wildly speculate this is because you are the Github owner and you have a custom `packages.json` that only includes `{emphatic}` which is the only package I see at https://coolbutuseless.r-universe.dev/packages
* Could be nice to have auto-built binaries with all the vignettes you wrote especially since CRAN makes us omit many of them due to size concerns...

**Comment by coolbutuseless** [comment]
I think it's well past time I transfer ggpattern to your account!

What do you think?

Let me look into what needs to be done.

**Comment by trevorld** [comment]
* I'm fine if it stays in your account or if you want to transfer it to my account (or perhaps transfer to some organization?).  I do also maintain the `{getopt}` package in my personal account and that was originally written by Allen Day.
* If you do want to transfer it I think there is a button on the bottom of "Settings" in the "Danger Zone".
* It would be good if R-universe could generate some package tarballs with all the vignettes and we could suggest users install from there in the README.
* Also would be good if there was an easier way for me to update the `{pgkdown}` website.

**Comment by coolbutuseless** [comment]
Hey @trevorld ,  If you agree, I will transfer {ggpattern} to your personal account.  Let me know.

**Comment by trevorld** [comment]
I agree to a transfer of `{ggpattern}` to my personal account (if you think that is what makes most sense or is easiest).

**Comment by coolbutuseless** [comment]
Transfer in progress!

**Comment by trevorld** [comment]
Okay, thanks!
